    # 1. Install Software (nano)
    # 2. Network Settings
    #     - Set IPv4 Forwarding (For Angular Container)
    #     - Open Port 6556 (For Check Mk Agent)
    # 3. Check MK Agent
    #     - Copy Package From Repo
    #     - Install Package
    #     - Install Xinetd
    #     - Copy Check Mk Config From Repo  
    #     - Restart Xinetd Service
          
    # Software
    #########################################################################################
  
    - name: Install Nano
      yum:
       name: nano
       state: latest

    # Network Settings
    #########################################################################################
    
    - debug:
       msg: Set IPv4 Forwarding For Docker Container

    - sysctl: 
       name: net.ipv4.ip_forward
       value: '1'
       sysctl_set: yes
       state: present
       reload: yes
    
    - name: Open Port 6556 (Firewall)
      shell: |
       firwall-cmd --permanent --add-port 6556/tcp
       firewall-cmd --reload

    # Check MK Agent
    #########################################################################################

    - name: Install Check Mk Agent 1/2 - Copy Package
      copy:
       src: ../../Monitoring/check-mk-agent-1.5.0p24-1.noarch.rpm
       dest: /root/
       owner: root
       group: root
    
    - name: Install Check Mk Agent 2/2 - Install Package
      yum:
       name: /root/check-mk-agent-1.5.0p24-1.noarch.rpm
       state: present

    - name: Install Xinetd
      yum:
       name: xinetd
       state: latest
    
    - name: Copy Check MK Config
      copy: 
       src: ../../CentOS Config/check_mk
       dest: /etc/xinetd.d/
       owner: root
       group: root

    - name: Restart Xinetd
      systemd:
       name: xinetd
       state: restarted