- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Include Ubuntu Tasks
      include_tasks: ubuntu.yml

- hosts: TestServers:ProductieServers
  become: yes
  remote_user: root

  tasks:

    - name: Include CentOS Tasks
      include_tasks: centos.yml
