    # 1. Install Packages (nodjs, npm, openssh-server, docker.io)
    # 2. Start Docker & SSH Service
    # 3. Jenkins
    #     - Create Container If Not Exists
    #     - Start Container If Stopped
    #     - Check Container State
    #     - Install JRE (Java) & SSHPASS (Required For Slave)
    # 4. Check MK
    #     - Create Container If Not Exists
    #     - Start Container If Stopped
    #     - Check Container State
    #     - Install CheckMk Agent & Xinetd
    # 5. ELK
    #     - Set vm.max_map_count
    #     - Create Container If Not Exists
    #     - Start Container If Stopped
    #     - Check Container State
    # 6. FileBeat
    #     - Install Filebeat
    #     - Copy Filebeat Configuration From Repo
    #     - Restart Filebeat Service
    #     - Setup Filebeat Dashboards

    # Install Packages 
    #########################################################################################
    
    - name: Install All Packages
      apt:
       pkg: 
       - nodejs
       - npm
       - openssh-server
       - docker.io
    
    # Start Services 
    #########################################################################################

    - name: Start Docker Service
      systemd:
       name: docker
       enabled: yes
       state: started      

    - name: Start SSH Service
      systemd:
       name: ssh
       enabled: yes
       state: started  

    # Jenkins (Container) + Slave 
    #########################################################################################
    
    - name: Jenkins - Get Container Info
      docker_container_info:
       name: jenkins_container
      register: jenkinsresult
      
    - name: Jenkins - Show Container State If Exists
      debug:
       msg: "The Jenkins Container Is {{ jenkinsresult.container['State']['Status'] }}"
      when: jenkinsresult.exists

    - name: Jenkins - Create And Start Container If Not Exist
      shell: |
       cd ../../ContainerScripts/
       ./jenkins.sh
      when: jenkinsresult.exists == False

    - name: Jenkins - Start Container If Not Running
      shell: docker start jenkins_container
      when: jenkinsresult.container['State']['Status'] != 'running'

    # (Required For Slave)

    - name: Install JRE & SSHPASS
      apt: 
       pkg: 
       - sshpass
       - default-jre

    # Check MK (Container) + Agent
    ######################################################################################### 

    - name: Check-mk - Get Container Info
      docker_container_info:
       name: monitoring_container
      register: monitoringresult

    - name: Check-mk - Show Container State If Exists
      debug:
       msg: "The Check_mk Container Is {{ monitoringresult.container['State']['Status'] }}"
      when: monitoringresult.exists

    - name: Check-mk - Create And Start Container If Not Exist
      shell: |
       cd ../../ContainerScripts/
       ./check_mk.sh
      when: monitoringresult.exists == False

    - name: Check-mk - Start Container If Not Running
      shell: docker start monitoring_container
      when: monitoringresult.container['State']['Status'] != 'running'

    # Check MK Agent

    - name: Install Check MK Agent & Xinetd
      apt: 
      pkg: 
      - check-mk-agent
      - xinetd

    # ELK Container + Filebeat
    ######################################################################################### 

    - name: Set vm.max_map_count
      shell: |
        cd ../../'Ubuntu Config'/
        cp sysctl.conf /etc/
        sysctl -p

    - name: ELK - Get Container Info
      docker_container_info:
       name: elk_container
      register: elkresult

    - name: ELK - Show Container State If Exist
      debug:
       msg: "The ELK Container Is {{ elkresult.container['State']['Status'] }}"
      when: elkresult.exists

    - name: ELK - Create And Start Container If Not Exist
      shell: |
       cd ../../ContainerScripts/
       ./ELK.sh
      when: elkresult.exists == False

    - name: ELK - Start Container If Not Running
      shell: docker start elk_container
      when: elkresult.container['State']['Status'] != 'running'

    # Filebeat

    - name: Install Filebeat
      apt:
       deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.7.0-amd64.deb

    - name: Copy Filebeat Configuration
      shell: |
       cd ../ELK/
       cp filebeat.yml /etc/filebeat/

    - name: Restart Filebeat Service
      systemd:
       name: filebeat
       state: restarted
      
    - name: Setup Filebeat Dashboards
      shell: filebeat setup --dashboards