- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Build Jenkins Pipeline
      shell: |
       cd StartJenkinsWithAnsible/
       ./startbuild.sh

- hosts: all
  become: yes
  remote_user: root

  tasks:
  
    - name: Docker Install Part 1/5 - Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Docker Install Part 2/5 - Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Docker Install Part 3/5 - Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Docker Install Part 4/5 - Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Docker Install part 5/5 - Install Docker Package
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
    
#    - name: Copy Github Project
#      copy:
#       src: /home/mohamed/Desktop/MM-Crypto
#       dest: /root

    - name: Install GIT
      package:
       name: git
       state: latest
      become: yes

    - name: Clone Github Repo
      git:
       repo: git@github.com:ElMoufid-Mohamed/DevOps-Project-Files.git
       version: master
       dest: /root/MM-Crypto
       accept_hostkey: yes

    - name: Stop All Containers
      shell: docker stop $(docker ps -a -q)

    - name: Remove All Containers
      shell: docker rm $(docker ps -a -q)

    - name: Remove Previous Image
      shell: docker rmi mm-crypto:v1

    - name: Build Container With Dockerfile
      shell: |
       cd /root/MM-Crypto/Web\ Application/MM-Crypto/
       docker build -t mm-crypto:v1 .

    - name: Run Container Detached
      shell: docker run -d -p 80:80 mm-crypto:v1

    - name: Check Container
      shell: docker ps
