- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Install NodeJS
      apt:
       name: nodejs
       state: present

    - name: Install NPM
      apt:
       name: npm
       state: present

    - name: Install Angular CLI 
      shell: npm install "@angular/cli"
#       name: "@angular/cli"
#       state: present
#       global: yes    


