    - name: Install NodeJS
      apt:
       name: nodejs
       state: present

    - name: Install NPM
      apt:
       name: npm
       state: present

    - name: Install Angular CLI 
      shell: npm install "@angular/cli"
